### ISSUE TITLE
New video resource for 'Middleware' topic from Laravel Daily yt channel!

### ISSUE THREAD

**Issue by alnahian2003** [LaravelDaily/Laravel-Roadmap-Learning-Path#30]
Hi!
I'm in the advanced beginner level of the roadmap. I think these video resources should be enlisted in the **Middleware** part. That might help others... and hopefully all of those videos are from LaravelDaily YouTube channel!
![image](https://user-images.githubusercontent.com/61485238/197403391-4b371660-cd18-472e-8f46-2e76b473c144.png)

**Video Resources on Laravel Middleware:**
1. **https://youtu.be/bnXauabSFYI**
2. **https://youtu.be/wmM9CFFpy34**
3. **https://youtu.be/_-Gv8s5NwqQ**
4. **https://youtu.be/UVvCcK0UJDg**

Thanks, Have a great day!

ALAN

**Comment by PovilasKorop** [comment]
@alnahian2003 thanks for the suggestion, but all those videos are about EXTRA information about Middlewares, more like tips&tricks, and not the fundamental things people need to learn about Middlewares.

If I had this logic, I would add all 1000+ of my videos to the roadmap, because they would be relevant to some topics anyway. But I deliberately chose to stay with the __essential__ links about every developer needs to know. If you have any links to share with that in mind, please make a Pull Request.

**Comment by alnahian2003** [comment]
Great, that makes sense!
Thanks for your reply 😀
